2024-03-12 16:31:48 | ERROR | 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.
2024-03-12 16:31:48 | ERROR | Traceback (most recent call last):
  File "C:\Users\roberttm\Documents\proyectos\App permisos y ausencias\app-permisos-ausencias\src\routes\PermissionRoutes.py", line 54, in create_permission
    dni = request.json['dni']
          ^^^^^^^^^^^^
  File "C:\Users\roberttm\Documents\proyectos\App permisos y ausencias\app-permisos-ausencias\.venv\Lib\site-packages\werkzeug\wrappers\request.py", line 558, in json
    return self.get_json()
           ^^^^^^^^^^^^^^^
  File "C:\Users\roberttm\Documents\proyectos\App permisos y ausencias\app-permisos-ausencias\.venv\Lib\site-packages\werkzeug\wrappers\request.py", line 604, in get_json
    return self.on_json_loading_failed(None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roberttm\Documents\proyectos\App permisos y ausencias\app-permisos-ausencias\.venv\Lib\site-packages\flask\wrappers.py", line 131, in on_json_loading_failed
    return super().on_json_loading_failed(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roberttm\Documents\proyectos\App permisos y ausencias\app-permisos-ausencias\.venv\Lib\site-packages\werkzeug\wrappers\request.py", line 647, in on_json_loading_failed
    raise UnsupportedMediaType(
werkzeug.exceptions.UnsupportedMediaType: 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.

2024-03-12 16:35:47 | ERROR | 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.
2024-03-12 16:35:47 | ERROR | Traceback (most recent call last):
  File "C:\Users\roberttm\Documents\proyectos\App permisos y ausencias\app-permisos-ausencias\src\routes\PermissionRoutes.py", line 54, in create_permission
    dni = request.json['dni']
          ^^^^^^^^^^^^
  File "C:\Users\roberttm\Documents\proyectos\App permisos y ausencias\app-permisos-ausencias\.venv\Lib\site-packages\werkzeug\wrappers\request.py", line 558, in json
    return self.get_json()
           ^^^^^^^^^^^^^^^
  File "C:\Users\roberttm\Documents\proyectos\App permisos y ausencias\app-permisos-ausencias\.venv\Lib\site-packages\werkzeug\wrappers\request.py", line 604, in get_json
    return self.on_json_loading_failed(None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roberttm\Documents\proyectos\App permisos y ausencias\app-permisos-ausencias\.venv\Lib\site-packages\flask\wrappers.py", line 131, in on_json_loading_failed
    return super().on_json_loading_failed(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roberttm\Documents\proyectos\App permisos y ausencias\app-permisos-ausencias\.venv\Lib\site-packages\werkzeug\wrappers\request.py", line 647, in on_json_loading_failed
    raise UnsupportedMediaType(
werkzeug.exceptions.UnsupportedMediaType: 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.

2024-03-12 16:35:52 | ERROR | 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.
2024-03-12 16:35:52 | ERROR | Traceback (most recent call last):
  File "C:\Users\roberttm\Documents\proyectos\App permisos y ausencias\app-permisos-ausencias\src\routes\PermissionRoutes.py", line 54, in create_permission
    dni = request.json['dni']
          ^^^^^^^^^^^^
  File "C:\Users\roberttm\Documents\proyectos\App permisos y ausencias\app-permisos-ausencias\.venv\Lib\site-packages\werkzeug\wrappers\request.py", line 558, in json
    return self.get_json()
           ^^^^^^^^^^^^^^^
  File "C:\Users\roberttm\Documents\proyectos\App permisos y ausencias\app-permisos-ausencias\.venv\Lib\site-packages\werkzeug\wrappers\request.py", line 604, in get_json
    return self.on_json_loading_failed(None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roberttm\Documents\proyectos\App permisos y ausencias\app-permisos-ausencias\.venv\Lib\site-packages\flask\wrappers.py", line 131, in on_json_loading_failed
    return super().on_json_loading_failed(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roberttm\Documents\proyectos\App permisos y ausencias\app-permisos-ausencias\.venv\Lib\site-packages\werkzeug\wrappers\request.py", line 647, in on_json_loading_failed
    raise UnsupportedMediaType(
werkzeug.exceptions.UnsupportedMediaType: 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.

2024-03-12 16:36:40 | ERROR | 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.
2024-03-12 16:36:40 | ERROR | Traceback (most recent call last):
  File "C:\Users\roberttm\Documents\proyectos\App permisos y ausencias\app-permisos-ausencias\src\routes\PermissionRoutes.py", line 54, in create_permission
    dni = request.json['dni']
          ^^^^^^^^^^^^
  File "C:\Users\roberttm\Documents\proyectos\App permisos y ausencias\app-permisos-ausencias\.venv\Lib\site-packages\werkzeug\wrappers\request.py", line 558, in json
    return self.get_json()
           ^^^^^^^^^^^^^^^
  File "C:\Users\roberttm\Documents\proyectos\App permisos y ausencias\app-permisos-ausencias\.venv\Lib\site-packages\werkzeug\wrappers\request.py", line 604, in get_json
    return self.on_json_loading_failed(None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roberttm\Documents\proyectos\App permisos y ausencias\app-permisos-ausencias\.venv\Lib\site-packages\flask\wrappers.py", line 131, in on_json_loading_failed
    return super().on_json_loading_failed(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roberttm\Documents\proyectos\App permisos y ausencias\app-permisos-ausencias\.venv\Lib\site-packages\werkzeug\wrappers\request.py", line 647, in on_json_loading_failed
    raise UnsupportedMediaType(
werkzeug.exceptions.UnsupportedMediaType: 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.

2024-03-12 17:09:40 | ERROR | 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.
2024-03-12 17:09:40 | ERROR | Traceback (most recent call last):
  File "C:\Users\roberttm\Documents\proyectos\App permisos y ausencias\app-permisos-ausencias\src\routes\PermissionRoutes.py", line 55, in create_permission
    dni = request.json['dni']
          ^^^^^^^^^^^^
  File "C:\Users\roberttm\Documents\proyectos\App permisos y ausencias\app-permisos-ausencias\.venv\Lib\site-packages\werkzeug\wrappers\request.py", line 558, in json
    return self.get_json()
           ^^^^^^^^^^^^^^^
  File "C:\Users\roberttm\Documents\proyectos\App permisos y ausencias\app-permisos-ausencias\.venv\Lib\site-packages\werkzeug\wrappers\request.py", line 604, in get_json
    return self.on_json_loading_failed(None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roberttm\Documents\proyectos\App permisos y ausencias\app-permisos-ausencias\.venv\Lib\site-packages\flask\wrappers.py", line 131, in on_json_loading_failed
    return super().on_json_loading_failed(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roberttm\Documents\proyectos\App permisos y ausencias\app-permisos-ausencias\.venv\Lib\site-packages\werkzeug\wrappers\request.py", line 647, in on_json_loading_failed
    raise UnsupportedMediaType(
werkzeug.exceptions.UnsupportedMediaType: 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.

2024-03-12 17:10:09 | ERROR | 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.
2024-03-12 17:10:09 | ERROR | Traceback (most recent call last):
  File "C:\Users\roberttm\Documents\proyectos\App permisos y ausencias\app-permisos-ausencias\src\routes\PermissionRoutes.py", line 55, in create_permission
    dni = request.json['dni']
          ^^^^^^^^^^^^
  File "C:\Users\roberttm\Documents\proyectos\App permisos y ausencias\app-permisos-ausencias\.venv\Lib\site-packages\werkzeug\wrappers\request.py", line 558, in json
    return self.get_json()
           ^^^^^^^^^^^^^^^
  File "C:\Users\roberttm\Documents\proyectos\App permisos y ausencias\app-permisos-ausencias\.venv\Lib\site-packages\werkzeug\wrappers\request.py", line 604, in get_json
    return self.on_json_loading_failed(None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roberttm\Documents\proyectos\App permisos y ausencias\app-permisos-ausencias\.venv\Lib\site-packages\flask\wrappers.py", line 131, in on_json_loading_failed
    return super().on_json_loading_failed(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roberttm\Documents\proyectos\App permisos y ausencias\app-permisos-ausencias\.venv\Lib\site-packages\werkzeug\wrappers\request.py", line 647, in on_json_loading_failed
    raise UnsupportedMediaType(
werkzeug.exceptions.UnsupportedMediaType: 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.

2024-03-12 17:14:01 | ERROR | 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.
2024-03-12 17:14:01 | ERROR | Traceback (most recent call last):
  File "C:\Users\roberttm\Documents\proyectos\App permisos y ausencias\app-permisos-ausencias\src\routes\PermissionRoutes.py", line 55, in create_permission
    dni = request.json['dni']
          ^^^^^^^^^^^^
  File "C:\Users\roberttm\Documents\proyectos\App permisos y ausencias\app-permisos-ausencias\.venv\Lib\site-packages\werkzeug\wrappers\request.py", line 558, in json
    return self.get_json()
           ^^^^^^^^^^^^^^^
  File "C:\Users\roberttm\Documents\proyectos\App permisos y ausencias\app-permisos-ausencias\.venv\Lib\site-packages\werkzeug\wrappers\request.py", line 604, in get_json
    return self.on_json_loading_failed(None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roberttm\Documents\proyectos\App permisos y ausencias\app-permisos-ausencias\.venv\Lib\site-packages\flask\wrappers.py", line 131, in on_json_loading_failed
    return super().on_json_loading_failed(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roberttm\Documents\proyectos\App permisos y ausencias\app-permisos-ausencias\.venv\Lib\site-packages\werkzeug\wrappers\request.py", line 647, in on_json_loading_failed
    raise UnsupportedMediaType(
werkzeug.exceptions.UnsupportedMediaType: 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.

2024-03-12 17:14:33 | ERROR | 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.
2024-03-12 17:14:33 | ERROR | Traceback (most recent call last):
  File "C:\Users\roberttm\Documents\proyectos\App permisos y ausencias\app-permisos-ausencias\src\routes\PermissionRoutes.py", line 54, in create_permission
    dni = request.json['dni']
          ^^^^^^^^^^^^
  File "C:\Users\roberttm\Documents\proyectos\App permisos y ausencias\app-permisos-ausencias\.venv\Lib\site-packages\werkzeug\wrappers\request.py", line 558, in json
    return self.get_json()
           ^^^^^^^^^^^^^^^
  File "C:\Users\roberttm\Documents\proyectos\App permisos y ausencias\app-permisos-ausencias\.venv\Lib\site-packages\werkzeug\wrappers\request.py", line 604, in get_json
    return self.on_json_loading_failed(None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roberttm\Documents\proyectos\App permisos y ausencias\app-permisos-ausencias\.venv\Lib\site-packages\flask\wrappers.py", line 131, in on_json_loading_failed
    return super().on_json_loading_failed(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roberttm\Documents\proyectos\App permisos y ausencias\app-permisos-ausencias\.venv\Lib\site-packages\werkzeug\wrappers\request.py", line 647, in on_json_loading_failed
    raise UnsupportedMediaType(
werkzeug.exceptions.UnsupportedMediaType: 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.

2024-03-12 17:14:35 | ERROR | 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.
2024-03-12 17:14:35 | ERROR | Traceback (most recent call last):
  File "C:\Users\roberttm\Documents\proyectos\App permisos y ausencias\app-permisos-ausencias\src\routes\PermissionRoutes.py", line 54, in create_permission
    dni = request.json['dni']
          ^^^^^^^^^^^^
  File "C:\Users\roberttm\Documents\proyectos\App permisos y ausencias\app-permisos-ausencias\.venv\Lib\site-packages\werkzeug\wrappers\request.py", line 558, in json
    return self.get_json()
           ^^^^^^^^^^^^^^^
  File "C:\Users\roberttm\Documents\proyectos\App permisos y ausencias\app-permisos-ausencias\.venv\Lib\site-packages\werkzeug\wrappers\request.py", line 604, in get_json
    return self.on_json_loading_failed(None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roberttm\Documents\proyectos\App permisos y ausencias\app-permisos-ausencias\.venv\Lib\site-packages\flask\wrappers.py", line 131, in on_json_loading_failed
    return super().on_json_loading_failed(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roberttm\Documents\proyectos\App permisos y ausencias\app-permisos-ausencias\.venv\Lib\site-packages\werkzeug\wrappers\request.py", line 647, in on_json_loading_failed
    raise UnsupportedMediaType(
werkzeug.exceptions.UnsupportedMediaType: 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.

2024-03-12 17:14:37 | ERROR | 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.
2024-03-12 17:14:37 | ERROR | Traceback (most recent call last):
  File "C:\Users\roberttm\Documents\proyectos\App permisos y ausencias\app-permisos-ausencias\src\routes\PermissionRoutes.py", line 54, in create_permission
    dni = request.json['dni']
          ^^^^^^^^^^^^
  File "C:\Users\roberttm\Documents\proyectos\App permisos y ausencias\app-permisos-ausencias\.venv\Lib\site-packages\werkzeug\wrappers\request.py", line 558, in json
    return self.get_json()
           ^^^^^^^^^^^^^^^
  File "C:\Users\roberttm\Documents\proyectos\App permisos y ausencias\app-permisos-ausencias\.venv\Lib\site-packages\werkzeug\wrappers\request.py", line 604, in get_json
    return self.on_json_loading_failed(None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roberttm\Documents\proyectos\App permisos y ausencias\app-permisos-ausencias\.venv\Lib\site-packages\flask\wrappers.py", line 131, in on_json_loading_failed
    return super().on_json_loading_failed(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roberttm\Documents\proyectos\App permisos y ausencias\app-permisos-ausencias\.venv\Lib\site-packages\werkzeug\wrappers\request.py", line 647, in on_json_loading_failed
    raise UnsupportedMediaType(
werkzeug.exceptions.UnsupportedMediaType: 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.

2024-03-12 17:20:58 | ERROR | 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.
2024-03-12 17:20:58 | ERROR | Traceback (most recent call last):
  File "C:\Users\roberttm\Documents\proyectos\App permisos y ausencias\app-permisos-ausencias\src\routes\PermissionRoutes.py", line 54, in create_permission
    dni = request.json['dni']
          ^^^^^^^^^^^^
  File "C:\Users\roberttm\Documents\proyectos\App permisos y ausencias\app-permisos-ausencias\.venv\Lib\site-packages\werkzeug\wrappers\request.py", line 558, in json
    return self.get_json()
           ^^^^^^^^^^^^^^^
  File "C:\Users\roberttm\Documents\proyectos\App permisos y ausencias\app-permisos-ausencias\.venv\Lib\site-packages\werkzeug\wrappers\request.py", line 604, in get_json
    return self.on_json_loading_failed(None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roberttm\Documents\proyectos\App permisos y ausencias\app-permisos-ausencias\.venv\Lib\site-packages\flask\wrappers.py", line 131, in on_json_loading_failed
    return super().on_json_loading_failed(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roberttm\Documents\proyectos\App permisos y ausencias\app-permisos-ausencias\.venv\Lib\site-packages\werkzeug\wrappers\request.py", line 647, in on_json_loading_failed
    raise UnsupportedMediaType(
werkzeug.exceptions.UnsupportedMediaType: 415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'.

2024-03-13 22:46:37 | ERROR | el valor es demasiado largo para el tipo character varying(60)

2024-03-13 22:46:37 | ERROR | Traceback (most recent call last):
  File "D:\Terranova\proyectos\App control de permisos\src\services\PermissionService.py", line 86, in create_permission
    cursor.execute("""INSERT INTO permissions
psycopg2.errors.StringDataRightTruncation: el valor es demasiado largo para el tipo character varying(60)


